# Generated by Django 3.0.5 on 2020-04-12 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='submission_date',
            field=models.DateTimeField(default=datetime.date(2020, 4, 12)),
            preserve_default=False,
        ),
    ]
